- src: geerlingguy.git
- src: geerlingguy.apache
- src: geerlingguy.mysql
- src: geerlingguy.varnish
- src: geerlingguy.memcached
- src: geerlingguy.php
- src: geerlingguy.php-pecl
- src: geerlingguy.php-mysql
- src: geerlingguy.php-memcached
- src: geerlingguy.php-xdebug
- src: geerlingguy.php-xhprof
- src: geerlingguy.phpmyadmin
- src: geerlingguy.composer
- src: geerlingguy.drush
- src: geerlingguy.daemonize
- src: geerlingguy.mailhog
- src: geerlingguy.java
- src: geerlingguy.tomcat6
- src: geerlingguy.solr
- src: ANXS.nodejs
- src: rvm_io.rvm1-ruby
