- src: geerlingguy.git
  version: 1.1.1
- src: geerlingguy.apache
  version: 1.7.2
- src: geerlingguy.mysql
  version: 2.2.1
- src: geerlingguy.varnish
  version: 1.5.0
- src: geerlingguy.memcached
  version: 1.0.4
- src: geerlingguy.php
  version: 2.0.3
- src: geerlingguy.php-pecl
  version: 1.2.1
- src: geerlingguy.php-mysql
  version: 1.2.0
- src: geerlingguy.php-memcached
  version: 1.1.0
- src: geerlingguy.composer
  version: 1.4.0
- src: geerlingguy.drush
  version: 1.1.2
- src: geerlingguy.daemonize
  version: 1.1.0
- src: geerlingguy.mailhog
  version: 1.1.0
- src: geerlingguy.java
  version: 1.4.0
- src: geerlingguy.tomcat6
- src: geerlingguy.solr
  version: 2.1.0
- src: ANXS.nodejs
- src: rvm_io.rvm1-ruby
