---

- name: Create the AWS Virtual Private Cloud
  ec2_vpc_net:
    cidr_block: "{{ vpc.cidr_block }}"
    name: "{{ env }}"
    region: "{{ region }}"
    state: present
    tags: "{{ vpc.tags }}"
  register: ec2_vpc_net_out
