# tasks file for myapp_infra
- name: create vpc
  ec2_vpc:
    state: present
    cidr_block: 172.22.0.0/16
    resource_tags: { "Name":" {{ infra_name }}" }
    subnets: "{{ vpc_subnets }}"
    internet_gateway: True
    route_tables: "{{ route_tables }}"
    region: "{{ region }}"
    wait: yes
  register: vpc

#- name: create admin access
#  ec2_group:
#    name: admin_access
#    description: SSH access for admins
#    region: "{{ region }}"
#    vpc_id: "{{ vpc.vpc_id }}"
#    rules:
#      - proto: tcp
#        from_port: 22
#        to_port: 22
#        cidr_ip: 0.0.0.0/0
#  tags: security_groups
#  register: admin_access_group

- name: create app security group
  ec2_group:
    name: "{{ infra_name }}"
    description: "{{ infra_name }} security group"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 0
        to_port: 65535
        group_name: "{{ infra_name }}"
      - proto: udp
        from_port: 0
        to_port: 65535
        group_name: "{{ infra_name }}"
      - proto: icmp
        from_port: 0
        to_port: 0
        group_name: "{{ infra_name }}"
    vpc_id: "{{ vpc.vpc_id }}"
  tags: security_groups
  register: app_security_group
