---
#tasks file for asg

- name: Create AutoScale Group and LaunchConfig via cloudformation
  cloudformation: >
    stack_name={{ client_slug }}
    state=present
    region={{ region }}
    disable_rollback=true
    template=roles/dkan_aws_as_cf/files/dkan-cf-Multi_AZ-0.1.0.json
  args:
    template_parameters:
      InstanceType: "{{ instance_type }}"
      SSHLocation: "{{ ssh_location }}"
      #AvailabilityZones: "{{ availability_zones | join(',') }}"
      #Subnets: "{{ asg_subnets | join(',') }}"
      ImageId: "{{ image_id }}"
      KeyName: "{{ key_name }}"
      #SecurityGroups: "{{ lc_security_groups | join(',')}}"
      #LoadBalancerNames: "{{ load_balancers | join(',') }}"
      DBClass: "{{ db_class }}"
      DBName:  "{{ db_name }}"
      DBUser: "{{ db_user}}"
      GIT_URL: "{{ git_url}}"
      GIT_COMMIT: "{{ git_commit}}"
      DBPassword: "{{ db_password}}"
      WebServerCapacity: "{{ webserver_capacity }}"
    tags:
      Stack: "{{ tag_stack }}"

  register: stack
